export const STARTUP_MIGRATIONS = [
  "ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(20)",
  "ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(255)",
  "ALTER TABLE users ADD COLUMN IF NOT EXISTS employee_id VARCHAR(50)",
  "ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login TIMESTAMP",
  "ALTER TABLE users ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'Active'",
  "ALTER TABLE artisans ADD COLUMN IF NOT EXISTS email VARCHAR(255)",
  "ALTER TABLE artisans ADD COLUMN IF NOT EXISTS employee_id VARCHAR(50)",
  "ALTER TABLE job_cards ADD COLUMN IF NOT EXISTS maintenance_type TEXT",
  "ALTER TABLE job_cards ADD COLUMN IF NOT EXISTS failure_type TEXT",
  "ALTER TABLE job_cards ADD COLUMN IF NOT EXISTS safety_notes TEXT",
];
