export const STARTUP_MIGRATIONS = [
  "ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(20)",
  "ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(255)",
  "ALTER TABLE users ADD COLUMN IF NOT EXISTS employee_id VARCHAR(50)",
  "ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login TIMESTAMP",
  "ALTER TABLE users ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'Active'",
  "ALTER TABLE artisans ADD COLUMN IF NOT EXISTS email VARCHAR(255)",
  "ALTER TABLE artisans ADD COLUMN IF NOT EXISTS employee_id VARCHAR(50)",
  "ALTER TABLE job_cards ADD COLUMN IF NOT EXISTS maintenance_type TEXT",
  "ALTER TABLE job_cards ADD COLUMN IF NOT EXISTS failure_type TEXT",
  "ALTER TABLE job_cards ADD COLUMN IF NOT EXISTS safety_notes TEXT",
  "ALTER TABLE job_cards ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP WITH TIME ZONE",
  "ALTER TABLE job_cards ADD COLUMN IF NOT EXISTS archived_by TEXT",
  "ALTER TABLE job_cards ADD COLUMN IF NOT EXISTS archive_reason TEXT",
  "ALTER TABLE job_cards ADD COLUMN IF NOT EXISTS archive_bucket TEXT",
  "ALTER TABLE job_cards ADD COLUMN IF NOT EXISTS retrieved_at TIMESTAMP WITH TIME ZONE",
  "ALTER TABLE job_cards ADD COLUMN IF NOT EXISTS retrieved_by TEXT",
  "ALTER TABLE audit_logs ALTER COLUMN details TYPE TEXT USING details::text",
  `CREATE TABLE IF NOT EXISTS pm_schedules (
    id TEXT PRIMARY KEY,
    plant_id TEXT NOT NULL,
    plant_name TEXT NOT NULL,
    frequency TEXT NOT NULL,
    last_run TEXT,
    next_run TEXT NOT NULL,
    tasks JSONB NOT NULL DEFAULT '[]',
    priority TEXT NOT NULL DEFAULT 'Medium',
    notes TEXT,
    created_by TEXT,
    updated_by TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS notification_dispatches (
    id TEXT PRIMARY KEY,
    job_card_id TEXT,
    event_name TEXT NOT NULL,
    channel TEXT NOT NULL,
    recipients JSONB NOT NULL DEFAULT '[]',
    message TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'queued',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
  )`,
];
